# In the name of God

# کلمه هایی که حرف ی فارسی دارند یک بار دیگر با ی عربی یعنی ي نیز درج شده اند.
# برای اینکار کلید شیفت نگه داشته شده
desired_phrase = [
    "نرم‌افزار",
    "نرم افزار",
    "سخت‌افزار",
    "سخت افزار",
    "کامپیوتر",
    "کامپيوتر",
    "ChatGPT",
    "ChatGpt",
    "رایانه",
    "computer",
    "Computer",
    "هوش مصنوعی",
    "هوش‌مصنوعی",
    "AI",
    "developer",
    "Developer",
    "software",
    "Software",
    "programmer",
    "Programmer",
    "artificial intelligence",
    "Artificial intelligence",
    "Artificial Intelligence",
    "PyTorch",
    "pytorch",
    "TensorFlow",
    "tensorflow",
    "Internet",
    "internet",
    "اینترنت",
    "اينترنت",
    "Product Manager",
    "product manager",
    "Product manager",
    "Product Owner",
    "product owner",
    "Product owner",
    "System Architect",
    "system srchitect",
    "System architect",
    "Scrum Master",
    "scrum master",
    "Scrum master",
    "Scaled Agile Framework",
    "Scaled agile framework",
    "scaled agile framework",
    "Scaled Agile",
    "Scaled agile",
    "scaled agile",
    "Processor",
    "processor",
    "CPU",
    "GPU",
    "digital",
    "Digital",
    "data",
    "Data",
    "cell phone",
    "Cell phone",
    "Mobile",
    "mobile",
    "development",
    "Development",
    "develop",
    "Develop",
    "اپلیکیشن",
    "اپليکيشن",
    "برنامه کاربردی",
    "دیجیتال",
    "دیجيتال",
    "داده‌ها",
    "داده ها",
    "سایبر",
    "سايبر",
    "گوشی",
    "گوشي",
    "programming language",
    "hacker",
    "Hacker",
    "هکر",
    "کدنویسی",
    "کد‌نویسی",
    "کد نویسی",
]

sites = [
    "https://www.inif.ir/",
    "https://www.isna.ir/service/Science-Academia/",
    "https://www.mehrnews.com/",
    "https://donya-e-eqtesad.com",
    "https://class.vision",
    "https://www.forbes.com/",
    "https://ana.press/",
    "https://www.aparat.com/ISNA",
    "https://irandoc.ac.ir/news",
    "https://newsroom.ibm.com/",
    "https://www.sepinud.org/",
    "https://www.sena.ir/",
    "https://masireqtesad.ir/",
    "https://www.sharif.edu/",
    "https://ce.sharif.edu",
    "https://kntu.ac.ir/",
    "https://aut.ac.ir/",
    "https://ce.aut.ac.ir/fa",
    "https://www.iut.ac.ir/fa",
    "https://techmart.ir/",
]
# ----------------------------------------------------------

should_send_to_chat = True
